# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_competitions_design_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='played_games_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='played_games_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
